'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PMD_Blue_S_and_Q_Route_Helper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Forest__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Forest__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Forest__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Forest__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Forest__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Forest__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Forest__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Forest__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Forest__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Forest__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Forest__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Forest__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Forest__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Forest__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Forest__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Forest__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Forest__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Forest__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Grotto__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Grotto__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Grotto__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Grotto__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Grotto__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Grotto__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Grotto__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Grotto__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frosty_Grotto__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frosty_Grotto__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__10F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__10F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__11F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__11F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__12F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__12F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__4F_alt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__4F_alt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__7F_alt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__7F_alt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Great_Canyon_10F___matýbe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great_Canyon_10F___matýbe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__10F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__10F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__11F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__11F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__12F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__12F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__13F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__13F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__14F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__14F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lapis_Cave__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lapis_Cave__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__10F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__10F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__11F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__11F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__12F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__12F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__13F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__13F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__14F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__14F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__15F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__15F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__16F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__16F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__17F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__17F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__18F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__18F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__19F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__19F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__20F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__20F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__21F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__21F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__22F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__22F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__23F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__23F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Magma_Cavern__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Magma_Cavern__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property mail() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("mail", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__10F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__10F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__11F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__11F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__12F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__12F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze_Peak_1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze_Peak_1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze_Peak_2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze_Peak_2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Blaze_Peak_3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Blaze_Peak_3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__10F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__10F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__11F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__11F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__12F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__12F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__13F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__13F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__14F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__14F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__15F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__15F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze_Peak_1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze_Peak_1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze_Peak_2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze_Peak_2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze_Peak_3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze_Peak_3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Freeze_Peak_4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Freeze_Peak_4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Steel__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Steel__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Steel__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Steel__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Steel__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Steel__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Steel__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Steel__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Steel__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Steel__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Steel__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Steel__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Steel__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Steel__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Steel__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Steel__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Steel__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Steel__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__10F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__10F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder_Peak_1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder_Peak_1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder_Peak_2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder_Peak_2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mt_Thunder_Peak_3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mt_Thunder_Peak_3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silent_Chasm__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Chasm__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silent_Chasm__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Chasm__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silent_Chasm__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Chasm__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silent_Chasm__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Chasm__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silent_Chasm__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Chasm__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silent_Chasm__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Chasm__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silent_Chasm__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Chasm__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silent_Chasm__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Chasm__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Silent_Chasm__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Silent_Chasm__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__10F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__10F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__11F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__11F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__12F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__12F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sinister_Woods__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sinister_Woods__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__10F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__10F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__11F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__11F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__12F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__12F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__13F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__13F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__14F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__14F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__15F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__15F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__16F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__16F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__17F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__17F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__18F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__18F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__19F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__19F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__20F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__20F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__21F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__21F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__22F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__22F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__23F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__23F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__24F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__24F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__25F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__25F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower_Summit_1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower_Summit_1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower_Summit_2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower_Summit_2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower_Summit_3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower_Summit_3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower_Summit_4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower_Summit_4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower_Summit_5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower_Summit_5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower_Summit_6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower_Summit_6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower_Summit_7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower_Summit_7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sky_Tower_Summit_8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sky_Tower_Summit_8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thunderwave_Cave__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thunderwave_Cave__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thunderwave_Cave__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thunderwave_Cave__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thunderwave_Cave__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thunderwave_Cave__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thunderwave_Cave__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thunderwave_Cave__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thunderwave_Cave__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thunderwave_Cave__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tiny_Woods__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tiny_Woods__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tiny_Woods__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tiny_Woods__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tiny_Woods__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tiny_Woods__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uproar_Forest__1F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uproar_Forest__1F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uproar_Forest__2F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uproar_Forest__2F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uproar_Forest__3F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uproar_Forest__3F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uproar_Forest__4F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uproar_Forest__4F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uproar_Forest__5F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uproar_Forest__5F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uproar_Forest__6F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uproar_Forest__6F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uproar_Forest__7F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uproar_Forest__7F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uproar_Forest__8F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uproar_Forest__8F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uproar_Forest__9F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uproar_Forest__9F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
